/**
 * Centralized SEO route metadata for Stooplify.
 * Used by: index.html preboot script, SEO component, sitemap, and internal link helpers.
 */

const OG_IMAGE = 'https://qtrypzzcjebvfcihiynt.supabase.co/storage/v1/object/public/base44-prod/public/6963ddb3a6f317a7cba3c5d6/Stooplify-07-favicon.png';
const SITE_NAME = 'Stooplify';
const BASE_URL = 'https://stooplify.com';

export const ROUTE_META = {
  '/': {
    title: 'Brooklyn Stoop Sales, Yard Sales & Garage Sales This Weekend | Stooplify',
    description: 'Find Brooklyn stoop sales, NYC yard sales, and garage sales happening near you this weekend. Browse live listings, save favorites, and list your own sale for free.',
    keywords: 'brooklyn stoop sale, stoop sales nyc, yard sales near me this weekend, garage sales brooklyn, nyc yard sales',
    robots: 'index, follow',
    type: 'website',
  },
  '/yard-sales': {
    title: 'Yard Sales & Stoop Sales Near Me This Weekend | Stooplify',
    description: 'Browse upcoming yard sales, stoop sales, and garage sales near you on an interactive map. Filter by category, date, and distance.',
    keywords: 'yard sales near me, stoop sales near me, garage sales this weekend, local yard sales',
    robots: 'index, follow',
    type: 'website',
  },
  '/add-yard-sale': {
    title: 'List Your Yard Sale or Stoop Sale for Free | Stooplify',
    description: 'List your yard sale, stoop sale, or garage sale in minutes. Reach thousands of local buyers in NYC. First listing is always free.',
    keywords: 'list yard sale, post garage sale, stoop sale listing, free yard sale listing',
    robots: 'index, follow',
    type: 'website',
  },
  '/guides': {
    title: 'Yard Sale Guides: Permits, Pricing, Advertising & Timing | Stooplify',
    description: 'Complete guides for hosting and finding yard sales in NYC. Learn about permits, pricing, best days to sell, how to advertise, and tips for buyers and seniors.',
    keywords: 'yard sale guides, how to host a yard sale, garage sale tips nyc, yard sale permit nyc, yard sale pricing guide',
    robots: 'index, follow',
    type: 'website',
  },
  '/guides-advertise-yard-sale': {
    title: 'How to Advertise a Yard Sale in NYC — Free & Easy Methods | Stooplify',
    description: 'The best free ways to advertise your yard sale or stoop sale in NYC. Reach local buyers in Brooklyn, Queens, and Manhattan without spending a dollar.',
    keywords: 'advertise yard sale, advertise garage sale, promote stoop sale nyc, free yard sale advertising brooklyn',
    robots: 'index, follow',
    type: 'article',
  },
  '/guides-best-time-yard-sale': {
    title: 'Best Days & Times to Host a Yard Sale in NYC | Stooplify',
    description: 'When is the best time to have a yard sale in New York City? Learn the optimal days, times, and seasons to maximize foot traffic and sales.',
    keywords: 'best time yard sale nyc, when to have garage sale, best day for stoop sale, yard sale timing',
    robots: 'index, follow',
    type: 'article',
  },
  '/guides-find-yard-sales': {
    title: 'How to Find Yard Sales Near You This Weekend | Stooplify',
    description: 'The easiest ways to find yard sales, stoop sales, and garage sales near you in NYC this weekend. Apps, maps, and local tips that actually work.',
    keywords: 'how to find yard sales near me, find stoop sales nyc, garage sales this weekend, where to find yard sales',
    robots: 'index, follow',
    type: 'article',
  },
  '/guides-permit-requirements-nyc': {
    title: 'Do You Need a Permit for a Yard Sale in NYC? | Stooplify',
    description: 'Find out if you need a permit to hold a yard sale, stoop sale, or garage sale in New York City. Simple rules for Brooklyn, Queens, Manhattan, and the Bronx.',
    keywords: 'yard sale permit nyc, garage sale permit new york, stoop sale rules brooklyn, do you need permit yard sale',
    robots: 'index, follow',
    type: 'article',
  },
  '/guides-pricing-yard-sale-items': {
    title: 'How to Price Items for a Yard Sale — What Actually Sells | Stooplify',
    description: "Learn how to price your yard sale and stoop sale items so they actually sell. Simple rules for furniture, clothing, electronics, and more.",
    keywords: 'how to price yard sale items, garage sale pricing guide, stoop sale prices, what to charge at yard sale',
    robots: 'index, follow',
    type: 'article',
  },
  '/guides-seniors-yard-sales': {
    title: 'How Seniors Can Post a Yard Sale Online (Step-by-Step) | Stooplify',
    description: 'A simple step-by-step guide for seniors on how to post a yard sale or estate sale online without any tech stress. Easy enough for anyone.',
    keywords: 'seniors yard sale guide, how to post yard sale online, easy garage sale listing, estate sale guide seniors',
    robots: 'index, follow',
    type: 'article',
  },
  '/what-is-a-stoop-sale': {
    title: 'What Is a Stoop Sale? NYC\'s Sidewalk Yard Sale Tradition | Stooplify',
    description: 'A stoop sale is NYC\'s version of a yard sale — held on front stoops and sidewalks. Learn the history, how they work, and where to find them this weekend.',
    keywords: 'what is a stoop sale, stoop sale meaning, stoop sale nyc, stoop sale tradition brooklyn',
    robots: 'index, follow',
    type: 'article',
  },
  '/stoop-sale-vs-yard-sale': {
    title: 'Stoop Sale vs. Yard Sale vs. Garage Sale: What\'s the Difference? | Stooplify',
    description: 'What\'s the difference between a stoop sale, yard sale, and garage sale? Learn the key differences and how each one works in NYC and beyond.',
    keywords: 'stoop sale vs yard sale, stoop sale vs garage sale, difference stoop sale yard sale, what is stoop sale',
    robots: 'index, follow',
    type: 'article',
  },
  '/how-to-host-a-stoop-sale': {
    title: 'How to Host a Stoop Sale in NYC — Complete Guide | Stooplify',
    description: 'Everything you need to know to host a successful stoop sale in New York City. From permits to pricing, advertising to setup — we cover it all.',
    keywords: 'how to host stoop sale, stoop sale guide, host yard sale nyc, stoop sale tips brooklyn',
    robots: 'index, follow',
    type: 'article',
  },
  '/best-time-for-yard-sales': {
    title: 'Best Time of Year for Yard Sales in NYC | Stooplify',
    description: 'When are the best months for yard sales in New York? Learn peak stoop sale season, weekend timing, and weather tips that maximize buyers.',
    keywords: 'best time year yard sale nyc, yard sale season new york, when to have stoop sale',
    robots: 'index, follow',
    type: 'article',
  },
  '/stoop-sales-brooklyn': {
    title: 'Brooklyn Stoop Sales This Weekend — Browse Live Listings | Stooplify',
    description: 'Find Brooklyn stoop sales and yard sales happening this weekend. Browse live listings in Park Slope, Williamsburg, Bushwick, Crown Heights, and more.',
    keywords: 'brooklyn stoop sales, stoop sales brooklyn this weekend, brooklyn yard sales, park slope stoop sale',
    robots: 'index, follow',
    type: 'website',
  },
  '/stoop-sales-queens': {
    title: 'Queens Stoop Sales & Yard Sales This Weekend | Stooplify',
    description: 'Discover stoop sales and yard sales in Queens this weekend. Browse listings in Astoria, Jackson Heights, Flushing, and surrounding neighborhoods.',
    keywords: 'queens stoop sales, yard sales queens nyc, astoria stoop sale, jackson heights yard sale',
    robots: 'index, follow',
    type: 'website',
  },
  '/stoop-sales-manhattan': {
    title: 'Manhattan Stoop Sales & Yard Sales This Weekend | Stooplify',
    description: 'Browse Manhattan stoop sales and yard sales happening this weekend. Find listings on the Upper West Side, Harlem, Washington Heights, and more.',
    keywords: 'manhattan stoop sales, nyc yard sales manhattan, upper west side stoop sale, harlem yard sale',
    robots: 'index, follow',
    type: 'website',
  },
  '/stoop-sales-bronx': {
    title: 'Bronx Stoop Sales & Yard Sales This Weekend | Stooplify',
    description: 'Find yard sales and stoop sales in the Bronx this weekend. Browse listings in Riverdale, Fordham, Pelham Bay, and neighborhoods across the borough.',
    keywords: 'bronx stoop sales, bronx yard sales, yard sales bronx nyc, bronx garage sales',
    robots: 'index, follow',
    type: 'website',
  },
  '/stoop-sales-jersey-city': {
    title: 'Jersey City Stoop Sales & Yard Sales This Weekend | Stooplify',
    description: 'Browse stoop sales and yard sales in Jersey City this weekend. Find listings in the Heights, Downtown JC, Bergen-Lafayette, and more.',
    keywords: 'jersey city stoop sales, jersey city yard sales, jc garage sales, hoboken yard sale',
    robots: 'index, follow',
    type: 'website',
  },
  '/garage-sales-nyc': {
    title: 'NYC Garage Sales This Weekend — All Five Boroughs | Stooplify',
    description: 'Find garage sales, yard sales, and stoop sales across all five NYC boroughs this weekend. Browse live listings in Brooklyn, Queens, Manhattan, the Bronx, and Staten Island.',
    keywords: 'nyc garage sales, garage sales new york city, nyc yard sales this weekend, garage sales brooklyn queens manhattan',
    robots: 'index, follow',
    type: 'website',
  },
  '/garage-sales-brooklyn': {
    title: 'Brooklyn Garage Sales This Weekend — Browse Live Listings | Stooplify',
    description: 'Browse garage sales and yard sales in Brooklyn this weekend. Find listings in Williamsburg, Park Slope, Bushwick, and every Brooklyn neighborhood.',
    keywords: 'brooklyn garage sales, garage sales brooklyn nyc, brooklyn yard sales this weekend',
    robots: 'index, follow',
    type: 'website',
  },
  '/garage-sales-manhattan': {
    title: 'Manhattan Garage Sales & Yard Sales This Weekend | Stooplify',
    description: 'Find garage sales and stoop sales in Manhattan this weekend. Browse listings across the Upper West Side, Harlem, Midtown, and Lower Manhattan.',
    keywords: 'manhattan garage sales, garage sales manhattan nyc, nyc apartment cleanout sales',
    robots: 'index, follow',
    type: 'website',
  },
  '/garage-sales-queens': {
    title: 'Queens Garage Sales & Yard Sales This Weekend | Stooplify',
    description: 'Find garage sales and yard sales in Queens this weekend. Browse listings in Astoria, Jackson Heights, Flushing, Forest Hills, and more.',
    keywords: 'queens garage sales, garage sales queens nyc, flushing yard sale, astoria garage sale',
    robots: 'index, follow',
    type: 'website',
  },
  '/garage-sales-bronx': {
    title: 'Bronx Garage Sales & Yard Sales This Weekend | Stooplify',
    description: 'Discover garage sales and yard sales in the Bronx this weekend. Browse listings in Riverdale, Fordham, Co-op City, and across the borough.',
    keywords: 'bronx garage sales, garage sales bronx nyc, bronx yard sales this weekend',
    robots: 'index, follow',
    type: 'website',
  },
  '/garage-sales-san-francisco': {
    title: 'San Francisco Garage Sales & Yard Sales This Weekend | Stooplify',
    description: 'Find garage sales and yard sales in San Francisco this weekend. Browse listings across the Mission, Castro, Haight-Ashbury, and all SF neighborhoods.',
    keywords: 'san francisco garage sales, sf yard sales, garage sales san francisco this weekend, mission district yard sale',
    robots: 'index, follow',
    type: 'website',
  },
  '/garage-sales-los-angeles': {
    title: 'Los Angeles Garage Sales & Yard Sales This Weekend | Stooplify',
    description: 'Browse garage sales and yard sales in Los Angeles this weekend. Find listings in Silver Lake, Echo Park, Los Feliz, Pasadena, and more.',
    keywords: 'los angeles garage sales, la yard sales this weekend, garage sales la, silver lake yard sale',
    robots: 'index, follow',
    type: 'website',
  },
  '/free-items': {
    title: 'Free Stuff Near Me — Free Items from Local Yard Sales | Stooplify',
    description: 'Browse free items from neighbors near you. Find furniture, clothing, and household goods being given away for free in NYC and beyond.',
    keywords: 'free stuff near me, free items nyc, free furniture near me, free giveaway items, curbside free stuff',
    robots: 'index, follow',
    type: 'website',
  },
  '/free-stuff-nyc': {
    title: 'Free Stuff NYC — Free Items From Neighbors Near You | Stooplify',
    description: 'Find free stuff in NYC from neighbors giving away furniture, clothing, books, and more. Browse free items across Brooklyn, Queens, Manhattan, and the Bronx.',
    keywords: 'free stuff nyc, free items new york, free furniture nyc, nyc freecycle, free stuff brooklyn',
    robots: 'index, follow',
    type: 'website',
  },
  '/blog': {
    title: 'Yard Sale Tips, Guides & NYC Selling News | Stooplify Blog',
    description: 'Tips, guides, and stories about yard sales, stoop sales, and garage sales in NYC and beyond. Learn how to buy smart, sell fast, and find hidden gems.',
    keywords: 'yard sale blog, stoop sale tips, garage sale guide, nyc selling tips, yard sale news',
    robots: 'index, follow',
    type: 'website',
  },
  '/calendar': {
    title: 'Yard Sale Calendar — Upcoming Sales This Weekend | Stooplify',
    description: 'Browse all upcoming yard sales, stoop sales, and garage sales by date. Plan your weekend treasure-hunting route on the Stooplify calendar.',
    keywords: 'yard sale calendar, upcoming yard sales, garage sales this weekend, stoop sale schedule nyc',
    robots: 'index, follow',
    type: 'website',
  },
  '/site-map': {
    title: 'Site Map | Stooplify',
    description: 'Full site map for Stooplify — find all pages including city guides, seller resources, and neighborhood listings.',
    keywords: 'stooplify site map',
    robots: 'index, follow',
    type: 'website',
  },
};

/** Returns meta for a given pathname, with sensible Stooplify defaults. */
export function getRouteMeta(pathname) {
  // strip trailing slash, normalize
  const path = pathname.replace(/\/$/, '') || '/';
  return ROUTE_META[path] || {
    title: 'Find Yard Sales & Stoop Sales Near You | Stooplify',
    description: 'Discover yard sales, stoop sales, and garage sales near you in NYC and beyond. List your own sale for free.',
    keywords: 'yard sale, stoop sale, garage sale, nyc, brooklyn',
    robots: 'index, follow',
    type: 'website',
  };
}

/** Canonical public URL path helper — always lowercase, hyphenated */
export const CANONICAL_ROUTES = {
  home: '/',
  'yard-sales': '/yard-sales',
  'add-yard-sale': '/add-yard-sale',
  guides: '/guides',
  blog: '/blog',
  calendar: '/calendar',
  pricing: '/pricing',
  favorites: '/favorites',
  profile: '/profile',
  messages: '/messages',
  'my-yard-sales': '/my-yard-sales',
  'free-items': '/free-items',
  'free-stuff-nyc': '/free-stuff-nyc',
  'free-stuff-brooklyn': '/free-stuff-brooklyn',
  'free-stuff-queens': '/free-stuff-queens',
  'stoop-sales-brooklyn': '/stoop-sales-brooklyn',
  'stoop-sales-queens': '/stoop-sales-queens',
  'stoop-sales-manhattan': '/stoop-sales-manhattan',
  'stoop-sales-bronx': '/stoop-sales-bronx',
  'stoop-sales-jersey-city': '/stoop-sales-jersey-city',
  'garage-sales-nyc': '/garage-sales-nyc',
  'garage-sales-brooklyn': '/garage-sales-brooklyn',
  'garage-sales-manhattan': '/garage-sales-manhattan',
  'garage-sales-queens': '/garage-sales-queens',
  'garage-sales-bronx': '/garage-sales-bronx',
  'garage-sales-san-francisco': '/garage-sales-san-francisco',
  'garage-sales-los-angeles': '/garage-sales-los-angeles',
};

/** Redirect map: old PascalCase / legacy routes → canonical */
export const LEGACY_REDIRECTS = {
  '/Home': '/',
  '/YardSales': '/yard-sales',
  '/AddYardSale': '/add-yard-sale',
  '/Guides': '/guides',
  '/Blog': '/blog',
  '/Calendar': '/calendar',
  '/Pricing': '/pricing',
  '/Favorites': '/favorites',
  '/Profile': '/profile',
  '/Messages': '/messages',
  '/StoopSalesBrooklyn': '/stoop-sales-brooklyn',
  '/StoopSalesQueens': '/stoop-sales-queens',
  '/StoopSalesManhattan': '/stoop-sales-manhattan',
  '/StoopSalesBronx': '/stoop-sales-bronx',
  '/StoopSalesJerseyCity': '/stoop-sales-jersey-city',
  '/GarageSalesSanFrancisco': '/garage-sales-san-francisco',
  '/GarageSalesLosAngeles': '/garage-sales-los-angeles',
  '/GuidesFindSales': '/guides-find-yard-sales',
  '/GuidesPricing': '/guides-pricing-yard-sale-items',
  '/GuidesTimings': '/guides-best-time-yard-sale',
  '/GuidesPermit': '/guides-permit-requirements-nyc',
  '/GuidesAdvertise': '/guides-advertise-yard-sale',
  '/GuidesSeniors': '/guides-seniors-yard-sales',
  '/FreeItems': '/free-items',
};